version: "3.1"
services:

    users: # can be accessed via:: (NO -external)|[users:8000]
      container_name: ${DB_CONTAINER}
      environment:
        TALK_WITH: ${WEB_CONTAINER}
        CONTAINER: ${DB_CONTAINER}
        DB_TYPE: ${DB_TYPE}
        DB_NAME: ${DB_NAME}
        DEV_ENV: ${APP_ENV}
      build: ./users
      image: nginx:alpine
      restart: always
      stdin_open: true
      tty: true
      expose: #accessed only for docker containers
        - "80"
      volumes:
        - ./db/:/tmp/db/
        - .env:/var/www/html/.env
        - ./users:/var/www/html
        - ./users/nginx-users.conf:/etc/nginx/conf.d/default.conf
      env_file:
        - .env
#      depends_on:
#        - phpfpm

    site: # can be accessed via:: (0.0.0.0:8000 -world)|[site:80 -internal,container]
      container_name: ${WEB_CONTAINER}
      environment:
        TALK_WITH: ${DB_CONTAINER}
        CONTAINER: ${WEB_CONTAINER}
        DEV_ENV: ${APP_ENV}
      build: ./site
      image: nginx:alpine
      restart: always
      ports: # world:container
        - "8000:80"
      volumes:
        - .env:/var/www/html/.env
        - ./site:/var/www/html
        - ./site/nginx-site.conf:/etc/nginx/conf.d/default.conf
#      depends_on:
#        - phpfpm
      env_file:
        - .env

# disabled, cause used   image: ngnix:apline
#    phpfpm:
#        image: phalconphp/phpfpm-fpm
#        restart: always
#        ports:
#            - "8080:80"
#        volumes:
#            - ./site/public:/var/www/public
##            - ./users/public:/var/www/public
#            - ./phpconfig/php.ini://etc/phpfpm/7.2/fpm/phpfpm.ini
#        depends_on:
#            - site
#        stdin_open: true
#        tty: true
