<?php

namespace AppUsers\Repository;

use Phalcon\Mvc\Collection;

//class Users extends Collection
class Users
{


    public function getDI()
    {
        parent::getDI(); // TODO: Change the autogenerated stub
    }


    public function getUserLiset()
    {
        return "user list";
    }

    public function getUser($username, $password)
    {
        return "search by {$username} and {$password}";
    }

}
